# Creates shipping Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable : 20
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - name: shipping
        image: 751732450123.dkr.ecr.us-east-1.amazonaws.com/shipping:502
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: shipping-configmap
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "200m"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-configmap
data:
  CART_ENDPOINT: cart-svc
  DB_HOST: "roboshop-dev-mysql.cni2x2uz4mfb.us-east-1.rds.amazonaws.com"
---

apiVersion: v1
kind: Service
metadata:
  name: shipping-svc
spec:
  selector:
    app: shipping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
# AutoScaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment   # This could be any scalable workload
    name: shipping
  minReplicas: 1     # Minimum number of replicas
  maxReplicas: 10     # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75   # Target average CPU utilization percentage

